/*
 * File: app/store/MyJsonStore2.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.store.MyJsonStore2', {
    extend: 'Ext.data.Store',

    requires: [
        'GOlineplus.model.poli',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore2',
            autoLoad: true,
            model: 'GOlineplus.model.poli',
            proxy: {
                type: 'ajax',
                url: 'http://192.168.88.22:8000/api/poli',
                actionMethods: {
                    read: 'GET'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});