/*
 * File: app/store/polis.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.store.polis', {
    extend: 'Ext.data.Store',
    alias: 'store.polis',

    requires: [
        'GOlineplus.model.poli',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'polis',
            model: 'GOlineplus.model.poli',
            data: '{[\n\n{"kodepoli":"9120","namapoli":"poli gigi dan mulut"},\n{"kodepoli":"9146","namapoli":"poli spesialis akupuntur"},\n{"kodepoli":"9130","namapoli":"poli spesialis anak"},\n{"kodepoli":"9141","namapoli":"poli spesialis bedah"},\n\n]}',
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});