/*
 * File: app/view/FormRawJal.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.view.FormRawJal', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.formrawjal',

    requires: [
        'GOlineplus.view.FormRawatJlnViewModel',
        'GOlineplus.view.FormRawatJlnViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.toolbar.Spacer',
        'Ext.form.field.TextArea'
    ],

    controller: 'formrawjal',
    viewModel: {
        type: 'formrawjal'
    },
    itemId: 'rawatPanel',
    scrollable: true,

    items: [
        {
            xtype: 'form',
            margin: '25 25 25 25',
            layout: 'auto',
            bodyPadding: 10,
            title: 'My Form',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    border: '1px',
                    dock: 'top',
                    height: 'auto',
                    margin: '50 50 50 50',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Jenis Pasien</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'radiogroup',
                                            width: 271,
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    labelPad: 3,
                                                    boxLabel: '<b>Pasien Lama</b>'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    boxLabel: '<b> Pasien Baru</b>'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '<b>Emboser</b>'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Unit</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 10',
                                            width: 350,
                                            name: 'unit'
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35,
                                            listeners: {
                                                click: 'onButtonClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Waktu</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'combobox',
                                            height: 35,
                                            margin: '0 0 0 10',
                                            width: 150,
                                            name: 'waktu',
                                            queryMode: 'local',
                                            store: [
                                                'PAGI',
                                                'SIANG',
                                                'SORE'
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Dokter</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 10',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35,
                                            listeners: {
                                                click: 'onBtnDokterClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Dokter Pengganti</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 10',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Referensi Dokter</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 10',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Urut Dari</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 10',
                                            width: 55
                                        },
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b> / No.Urut Poli</b></font>',
                                            margin: '0 5 0 10',
                                            width: 87
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 10',
                                            width: 55
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            height: 'auto',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 20,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>No.Transaksi</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 10 0 40',
                                            width: 195
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '<b>Telepon</b>'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Tanggal dan Waktu</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'datefield',
                                            height: 35,
                                            margin: '0 0 0 25',
                                            width: 195
                                        },
                                        {
                                            xtype: 'timefield',
                                            height: 35,
                                            margin: '0 0 0 10',
                                            width: 195
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Dari</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 0 0 25',
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Cara Kunjung</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'combobox',
                                            height: 35,
                                            margin: '0 0 0 25',
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Penanggung</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 0 0 41',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            margin: '0 0 0 15',
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Cara Membayar</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'combobox',
                                            height: 35,
                                            margin: '0 0 0 25',
                                            width: 400
                                        }
                                    ]
                                }
                            ],
                            items: [
                                {
                                    xtype: 'tbspacer',
                                    height: 38,
                                    width: 59
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    border: '1px',
                    dock: 'top',
                    height: 'auto',
                    margin: '50 50 50 50',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 'auto',
                                            html: '<font size="5pt" color="#3B7EE7"><b>Data Pasien</b></font>',
                                            width: 'auto'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>No.Pasien</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Nama panggilan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            itemId: 'namapanggilan',
                                            width: 400,
                                            name: 'namapanggilan'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Tempat Lahir</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Tanggal Lahir</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'datefield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Umur</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 0 0 15',
                                            width: 150
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Jenis Kelamin</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Agama</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'combobox',
                                            height: 35,
                                            margin: '0 0 0 15',
                                            width: 400
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            height: 'auto',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Nama Pasien</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Nama EYD</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Pendidikan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 100
                                        },
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#808080" size="2pt"><b>Golongan Darah</b></font>',
                                            margin: '0 9 0 10',
                                            width: 110
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 165
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Status</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 135
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            margin: '0 15 0 15',
                                            fieldLabel: '',
                                            boxLabel: '<b>WNI</b>'
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 0 0 20',
                                            width: 165
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Pekerjaan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 356
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35,
                                            listeners: {
                                                click: 'onBtnPekerjaClick'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Alergi</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>No.KTP</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    border: '1px',
                    dock: 'top',
                    height: 'auto',
                    margin: '50 50 50 50',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 'auto',
                                            html: '<font size="5pt" color="#3B7EE7"><b>Data Alamat</b></font>',
                                            width: 'auto'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Jalan / Dukuh</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Desa / Kelurahan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Kecamatan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Kota</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35,
                                            iconCls: 'x-fa fa-file-text-o'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Provinsi</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            height: 'auto',
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Kode Pos</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 160
                                        },
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Telepon</b></font>',
                                            margin: '0 0 0 10',
                                            width: 60
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 160
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Kantor</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt">Alamat Kantor<b></b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Telepon Kantor</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 356
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    border: '1px',
                    dock: 'top',
                    height: 'auto',
                    margin: '50 50 50 50',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 'auto',
                                            html: '<font size="5pt" color="#3B7EE7"><b>Data Penanggung Jawab </b></font>',
                                            width: 'auto'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Jenis Pasien</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>No.Kartu</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Penjamin</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Jenis Peserta</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'combobox',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Kode PKK 1</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 350
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            height: 'auto',
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Nama</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Hubungan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>No.Tanggungan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'combobox',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt">Alamat<b></b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Jatah Kelas</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'combobox',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    border: '1px',
                    dock: 'top',
                    height: 'auto',
                    margin: '50 50 50 50',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 'auto',
                                            html: '<font size="5pt" color="#3B7EE7"><b>Data Rujukan BPJS </b></font>',
                                            width: 'auto'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>No. SEP</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 250
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 136,
                                            iconCls: '',
                                            text: '<font color="#ffffff" ><b>GENERATE SEP</b></font>'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Tanggal SEP</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 150
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 19,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Diagnosa</b></font>',
                                            margin: '3 0 0 0',
                                            width: 113
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            margin: '0 15 0 15',
                                            width: 100
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 245
                                        },
                                        {
                                            xtype: 'button',
                                            height: 35,
                                            width: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>No Rujukan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Tanggal Rujukan</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'datefield',
                                            height: 35,
                                            width: 150
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            height: 'auto',
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 19,
                                    margin: '0 0 20 0'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            height: 200,
                                            padding: '',
                                            width: 535,
                                            fieldLabel: '<font color="#A2A0A0 " size="2pt"><b>Catatan</b></font>',
                                            labelPad: 25
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            margin: '0 0 0 125',
                                            boxLabel: '<b>Aktif Otomatis SEP</b>'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    border: '1px',
                    dock: 'top',
                    height: 'auto',
                    margin: '50 50 50 50',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 'auto',
                                            html: '<font size="5pt" color="#3B7EE7"><b>Data Keluarga</b></font>',
                                            width: 'auto'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Nama Ayah</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 150
                                        },
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Nama Ibu</b></font>',
                                            width: 85
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 150
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Alamat Sementara</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Kode Pos</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 160
                                        },
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Telepon</b></font>',
                                            margin: '0 0 0 10',
                                            width: 60
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 162
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Nama Suami/Istri</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            flex: 1,
                            height: 'auto',
                            margin: '',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    height: 45,
                                    margin: '0 0 20 0'
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt">Yang Dapat dihubungi<b></b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt">Hubungan<b></b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt"><b>Alamat</b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 26,
                                            html: '<font color="#A2A0A0 " size="2pt">Telepon<b></b></font>',
                                            margin: '3 0 0 0',
                                            width: 129
                                        },
                                        {
                                            xtype: 'textfield',
                                            height: 35,
                                            width: 400
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    border: '1px',
                    dock: 'top',
                    height: 95,
                    items: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            flex: 3,
                            items: [
                                {
                                    xtype: 'button',
                                    margins: '',
                                    height: 50,
                                    margin: '0 0 0 35',
                                    width: 186,
                                    text: '<font color="#ffffff" size="3pt" ><b>Rekam Data</b></font>'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            margins: '0 50 0 0',
                            flex: 1,
                            width: 627,
                            items: [
                                {
                                    xtype: 'button',
                                    height: 50,
                                    width: 120,
                                    text: '<font color="#ffffff" size="3pt"><b>Proses</b></font>',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 50,
                                    margin: '0 20 0 20',
                                    width: 120,
                                    text: '<font size="3pt" color="#ffffff" ><b>Cetak</b></font>'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});