/*
 * File: app/view/FormRawatJlnViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.view.FormRawatJlnViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.formrawjal',

    onButtonClick: function(button, e, eOpts) {
        var win = this.getView();

        win = Ext.create('widget.unitpelayananwindow');

        win.show();
    },

    onBtnDokterClick: function(button, e, eOpts) {
        var a = this.getView();

        a = Ext.create('widget.dokter');

        a.show();
    },

    onBtnPekerjaClick: function(button, e, eOpts) {
        var b = this.getView();

        b = Ext.create('widget.pekerjaan');

        b.show();
    },

    onButtonClick: function(button, e, eOpts) {
        var form = button.up('form'),
            values = form.getValues();


        var value = form. getForm (). findField ("namapanggilan"). getValue ();
        console.log(value);

    }

});
