/*
 * File: app/view/LoginFormViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.view.LoginFormViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginform',

    onLoginButtonClick: function(button, e, eOpts) {
        var view = this.getView(),
            me = this,
            form = button.up('form'),
            formWindow = button.up('window'),
            values = form.getValues();

        //Jika Berhasil mengirim data (Success)


        var sukses = function(response){
            var data = Ext.decode(response.responseText);
            console.log(data.success.token);
            if(data.success.token){
                view.destroy();
                Ext.widget('menu');
            }
        };

        //jika salah mengirim data (Error)
        var gagal = function(resp, ops) {
            Ext.Msg.alert('Login gagal','Username atau Password salah !');

        };





        Ext.Ajax.request({
            url: "http://192.168.88.22:8000/api/login",
            params: values,
            method: 'POST',
            cors: true,
            useDefaultXhrHeader:false,
            success: sukses,
            failure: gagal


        });


    }

});
