/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.view.LoginForm', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.loginform',

    requires: [
        'GOlineplus.view.LoginFormViewModel',
        'GOlineplus.view.LoginFormViewController',
        'Ext.Img',
        'Ext.toolbar.Spacer',
        'Ext.form.Panel',
        'Ext.form.Label',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'loginform',
    viewModel: {
        type: 'loginform'
    },
    height: '100%',
    scrollable: true,
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            flex: 1,
            region: 'west',
            flex: 1,
            width: 150,
            title: '',
            items: [
                {
                    xtype: 'image',
                    height: '100%',
                    width: '100%',
                    src: 'images/bg_login.png',
                    title: ''
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'center',
            flex: 1,
            items: [
                {
                    xtype: 'tbspacer',
                    height: '30%',
                    width: '100%'
                },
                {
                    xtype: 'form',
                    border: false,
                    height: '100%',
                    margin: 30,
                    width: '100%',
                    layout: 'auto',
                    bodyPadding: 20,
                    jsonSubmit: false,
                    items: [
                        {
                            xtype: 'label',
                            html: '<font size="10pt"><b>Sign In</b></font>',
                            resizable: false
                        },
                        {
                            xtype: 'tbspacer',
                            height: 35,
                            width: 150
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10 0',
                            width: 300,
                            fieldLabel: 'Username',
                            labelAlign: 'top',
                            msgTarget: 'title',
                            name: 'username',
                            allowBlank: false,
                            blankText: 'Enter your Username.',
                            regexText: 'Enter your username.'
                        },
                        {
                            xtype: 'textfield',
                            margin: '0 0 10 0',
                            width: 300,
                            fieldLabel: 'Password',
                            labelAlign: 'top',
                            msgTarget: 'title',
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false,
                            blankText: 'Enter your password.'
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            margin: '0 15 0 0',
                            width: 200,
                            scale: 'large',
                            text: 'Login',
                            listeners: {
                                click: 'onLoginButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});