/*
 * File: app/view/Pekerjaan.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.view.Pekerjaan', {
    extend: 'Ext.window.Window',
    alias: 'widget.pekerjaan',

    requires: [
        'GOlineplus.view.DokterViewModel1',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'pekerjaan'
    },
    height: '',
    width: '40%',
    title: 'Pekerjaan',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            flex: 1,
            margin: '20 20 20 20',
            items: [
                {
                    xtype: 'combobox',
                    flex: 1,
                    flex: 1,
                    height: 35,
                    store: [
                        'Kode',
                        'Pekerjaaan'
                    ]
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    flex: 3,
                    height: 35,
                    margin: '0 0 0 20'
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            flex: 1,
            margin: '20 20 20 20',
            items: [
                {
                    xtype: 'combobox',
                    flex: 1,
                    flex: 1,
                    height: 35,
                    store: [
                        'Kode',
                        'Pekerjaaan'
                    ]
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    flex: 3,
                    height: 35,
                    margin: '0 0 0 20'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            reference: 'list',
            margin: '0 20 35 25',
            resizable: false,
            scrollable: true,
            title: '',
            forceFit: true,
            bind: {
                store: 'dataPoli'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'kodepoli',
                    text: 'Kode'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'center',
                    dataIndex: 'namapoli',
                    text: 'Pekerjaan'
                }
            ]
        }
    ]

});