/*
 * File: app/controller/navigation.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GOlineplus.controller.navigation', {
    extend: 'Ext.app.Controller',

    refs: {
        contentPanel: '#contentPanel',
        adm: '#adm'
    },

    onLaunch: function(application) {



        // Init the Ext history utility
        Ext.History.init();

        // Navigate on hash change
        Ext.History.on('change', this.navigate, this);

        // Navigate if initial hash is provided
        this.navigate(window.location.hash);


    },

    navigate: function(navigate) {

        // id may be a hash
        if (id) {

            // Remove # from id if present
            if (id[0] == '#') id = id.slice(1);

            // Set active view
            this.getContentPanel().layout.setActiveItem(id + 'Panel');

            // Set menu and page title
            // Iterate through each menu item
            this.getMenu().items.each(function(item) {

                // Active
                if (item.href == '#' + id) {
                    // Disable
                    item.disable();
                    // Set page title to menu item text
                    window.document.title = item.text;
                }

                // Inactive
                else {
                    item.enable();
                }

            });

        }

    }

});
